//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskbarReader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskbarReader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clock {
            get {
                object obj = ResourceManager.GetObject("clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon clock_icon {
            get {
                object obj = ResourceManager.GetObject("clock_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string en_about_author_label {
            get {
                return ResourceManager.GetString("en_about_author_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;ABOUT&lt;/b&gt;.
        /// </summary>
        internal static string en_about_button {
            get {
                return ResourceManager.GetString("en_about_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string en_about_email_label {
            get {
                return ResourceManager.GetString("en_about_email_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read TXT in Taskbar!&lt;br/&gt;Thank you for your support!.
        /// </summary>
        internal static string en_about_intro {
            get {
                return ResourceManager.GetString("en_about_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro.
        /// </summary>
        internal static string en_about_intro_label {
            get {
                return ResourceManager.GetString("en_about_intro_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string en_about_label {
            get {
                return ResourceManager.GetString("en_about_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string en_about_version_label {
            get {
                return ResourceManager.GetString("en_about_version_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 (sec).
        /// </summary>
        internal static string en_apt_end_label {
            get {
                return ResourceManager.GetString("en_apt_end_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Page Turn.
        /// </summary>
        internal static string en_apt_label {
            get {
                return ResourceManager.GetString("en_apt_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        internal static string en_apt_label_sec {
            get {
                return ResourceManager.GetString("en_apt_label_sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Page Turn Settings.
        /// </summary>
        internal static string en_apt_label2 {
            get {
                return ResourceManager.GetString("en_apt_label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 (sec)&lt;br/&gt;Manual.
        /// </summary>
        internal static string en_apt_start_label {
            get {
                return ResourceManager.GetString("en_apt_start_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (sec).
        /// </summary>
        internal static string en_apt_tooltip {
            get {
                return ResourceManager.GetString("en_apt_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed!&lt;br/&gt;Please try again later!.
        /// </summary>
        internal static string en_autoUpdater_msg_failed {
            get {
                return ResourceManager.GetString("en_autoUpdater_msg_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string en_autoUpdater_msg_failed_title {
            get {
                return ResourceManager.GetString("en_autoUpdater_msg_failed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!&lt;br/&gt;Application restarts in 5 seconds!.
        /// </summary>
        internal static string en_autoUpdater_msg_success {
            get {
                return ResourceManager.GetString("en_autoUpdater_msg_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string en_autoUpdater_msg_success_title {
            get {
                return ResourceManager.GetString("en_autoUpdater_msg_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update terminated!&lt;br/&gt;Cannot complete update!.
        /// </summary>
        internal static string en_autoUpdater_msg_terminated {
            get {
                return ResourceManager.GetString("en_autoUpdater_msg_terminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminated.
        /// </summary>
        internal static string en_autoUpdater_msg_terminated_title {
            get {
                return ResourceManager.GetString("en_autoUpdater_msg_terminated_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version already!.
        /// </summary>
        internal static string en_autoUpdater_result_latest {
            get {
                return ResourceManager.GetString("en_autoUpdater_result_latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update info found!.
        /// </summary>
        internal static string en_autoUpdater_result_none {
            get {
                return ResourceManager.GetString("en_autoUpdater_result_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark added!.
        /// </summary>
        internal static string en_bookmark_added {
            get {
                return ResourceManager.GetString("en_bookmark_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All bookmarks are deleted!.
        /// </summary>
        internal static string en_bookmark_all_deleted {
            get {
                return ResourceManager.GetString("en_bookmark_all_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting current bookmark!.
        /// </summary>
        internal static string en_bookmark_delete_error {
            get {
                return ResourceManager.GetString("en_bookmark_delete_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark exists!.
        /// </summary>
        internal static string en_bookmark_exists {
            get {
                return ResourceManager.GetString("en_bookmark_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bookmark found!.
        /// </summary>
        internal static string en_bookmark_none {
            get {
                return ResourceManager.GetString("en_bookmark_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Bookmarks.
        /// </summary>
        internal static string en_bookmarks {
            get {
                return ResourceManager.GetString("en_bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear bookmarks.
        /// </summary>
        internal static string en_bookmarks_clearall {
            get {
                return ResourceManager.GetString("en_bookmarks_clearall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        internal static string en_bookmarks_none {
            get {
                return ResourceManager.GetString("en_bookmarks_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string en_button_cancel {
            get {
                return ResourceManager.GetString("en_button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string en_button_ok {
            get {
                return ResourceManager.GetString("en_button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string en_exit {
            get {
                return ResourceManager.GetString("en_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide/Show.
        /// </summary>
        internal static string en_hideshow {
            get {
                return ResourceManager.GetString("en_hideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string en_history {
            get {
                return ResourceManager.GetString("en_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear history.
        /// </summary>
        internal static string en_history_clearall {
            get {
                return ResourceManager.GetString("en_history_clearall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove invalid history.
        /// </summary>
        internal static string en_history_clearinvalid {
            get {
                return ResourceManager.GetString("en_history_clearinvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        internal static string en_history_none {
            get {
                return ResourceManager.GetString("en_history_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;HOTKEYS&lt;/b&gt;.
        /// </summary>
        internal static string en_hotkey_button {
            get {
                return ResourceManager.GetString("en_hotkey_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key pressed!.
        /// </summary>
        internal static string en_hotkey_invalid_pressed {
            get {
                return ResourceManager.GetString("en_hotkey_invalid_pressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To....
        /// </summary>
        internal static string en_hotkey_label {
            get {
                return ResourceManager.GetString("en_hotkey_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark View.
        /// </summary>
        internal static string en_hotkey_label1 {
            get {
                return ResourceManager.GetString("en_hotkey_label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Actions.
        /// </summary>
        internal static string en_hotkey_label2 {
            get {
                return ResourceManager.GetString("en_hotkey_label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Hotkeys.
        /// </summary>
        internal static string en_hotkey_label3 {
            get {
                return ResourceManager.GetString("en_hotkey_label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register some of the hot keys!.
        /// </summary>
        internal static string en_hotkey_registration_failed {
            get {
                return ResourceManager.GetString("en_hotkey_registration_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next line.
        /// </summary>
        internal static string en_hotkey1 {
            get {
                return ResourceManager.GetString("en_hotkey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+X.
        /// </summary>
        internal static string en_hotkey1_label {
            get {
                return ResourceManager.GetString("en_hotkey1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current bookmark.
        /// </summary>
        internal static string en_hotkey10 {
            get {
                return ResourceManager.GetString("en_hotkey10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+D.
        /// </summary>
        internal static string en_hotkey10_label {
            get {
                return ResourceManager.GetString("en_hotkey10_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous line.
        /// </summary>
        internal static string en_hotkey2 {
            get {
                return ResourceManager.GetString("en_hotkey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+Z.
        /// </summary>
        internal static string en_hotkey2_label {
            get {
                return ResourceManager.GetString("en_hotkey2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark current line.
        /// </summary>
        internal static string en_hotkey3 {
            get {
                return ResourceManager.GetString("en_hotkey3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+A.
        /// </summary>
        internal static string en_hotkey3_label {
            get {
                return ResourceManager.GetString("en_hotkey3_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Bookmark View.
        /// </summary>
        internal static string en_hotkey4 {
            get {
                return ResourceManager.GetString("en_hotkey4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+S.
        /// </summary>
        internal static string en_hotkey4_label {
            get {
                return ResourceManager.GetString("en_hotkey4_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Bookmark View.
        /// </summary>
        internal static string en_hotkey5 {
            get {
                return ResourceManager.GetString("en_hotkey5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+C.
        /// </summary>
        internal static string en_hotkey5_label {
            get {
                return ResourceManager.GetString("en_hotkey5_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide / Show TaskbarReader.
        /// </summary>
        internal static string en_hotkey6 {
            get {
                return ResourceManager.GetString("en_hotkey6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+Space.
        /// </summary>
        internal static string en_hotkey6_label {
            get {
                return ResourceManager.GetString("en_hotkey6_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit TaskbarReader.
        /// </summary>
        internal static string en_hotkey7 {
            get {
                return ResourceManager.GetString("en_hotkey7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+Q.
        /// </summary>
        internal static string en_hotkey7_label {
            get {
                return ResourceManager.GetString("en_hotkey7_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous bookmark.
        /// </summary>
        internal static string en_hotkey8 {
            get {
                return ResourceManager.GetString("en_hotkey8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+A.
        /// </summary>
        internal static string en_hotkey8_label {
            get {
                return ResourceManager.GetString("en_hotkey8_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next bookmark.
        /// </summary>
        internal static string en_hotkey9 {
            get {
                return ResourceManager.GetString("en_hotkey9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+S.
        /// </summary>
        internal static string en_hotkey9_label {
            get {
                return ResourceManager.GetString("en_hotkey9_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide / Show TaskbarReader.
        /// </summary>
        internal static string en_mouse1 {
            get {
                return ResourceManager.GetString("en_mouse1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Double Click.
        /// </summary>
        internal static string en_mouse1_label {
            get {
                return ResourceManager.GetString("en_mouse1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open TXT.
        /// </summary>
        internal static string en_mouse2 {
            get {
                return ResourceManager.GetString("en_mouse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Click.
        /// </summary>
        internal static string en_mouse2_label {
            get {
                return ResourceManager.GetString("en_mouse2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show context menu.
        /// </summary>
        internal static string en_mouse3 {
            get {
                return ResourceManager.GetString("en_mouse3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Click.
        /// </summary>
        internal static string en_mouse3_label {
            get {
                return ResourceManager.GetString("en_mouse3_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One file at a time!.
        /// </summary>
        internal static string en_only_single_file {
            get {
                return ResourceManager.GetString("en_only_single_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT file only!.
        /// </summary>
        internal static string en_only_txt_file {
            get {
                return ResourceManager.GetString("en_only_txt_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open TXT.
        /// </summary>
        internal static string en_openFile {
            get {
                return ResourceManager.GetString("en_openFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text File|*.txt.
        /// </summary>
        internal static string en_openFileDialog_filter {
            get {
                return ResourceManager.GetString("en_openFileDialog_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a TXT file.
        /// </summary>
        internal static string en_openFileDialog_title {
            get {
                return ResourceManager.GetString("en_openFileDialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a TXT file here.
        /// </summary>
        internal static string en_pictureBox_string_1 {
            get {
                return ResourceManager.GetString("en_pictureBox_string_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR... Double click here.
        /// </summary>
        internal static string en_pictureBox_string_2 {
            get {
                return ResourceManager.GetString("en_pictureBox_string_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading: .
        /// </summary>
        internal static string en_pictureBox_string_3 {
            get {
                return ResourceManager.GetString("en_pictureBox_string_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already at the FIRST line!.
        /// </summary>
        internal static string en_readbackward_nomore {
            get {
                return ResourceManager.GetString("en_readbackward_nomore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already at the LAST line!.
        /// </summary>
        internal static string en_readforward_nomore {
            get {
                return ResourceManager.GetString("en_readforward_nomore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value!.
        /// </summary>
        internal static string en_timer_error {
            get {
                return ResourceManager.GetString("en_timer_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed: .
        /// </summary>
        internal static string en_update_completed {
            get {
                return ResourceManager.GetString("en_update_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cur Version.
        /// </summary>
        internal static string en_update_cur {
            get {
                return ResourceManager.GetString("en_update_cur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Description.
        /// </summary>
        internal static string en_update_description {
            get {
                return ResourceManager.GetString("en_update_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Update.
        /// </summary>
        internal static string en_update_download {
            get {
                return ResourceManager.GetString("en_update_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded: .
        /// </summary>
        internal static string en_update_downloaded {
            get {
                return ResourceManager.GetString("en_update_downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Update ....
        /// </summary>
        internal static string en_update_downloading {
            get {
                return ResourceManager.GetString("en_update_downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update found!.
        /// </summary>
        internal static string en_update_found {
            get {
                return ResourceManager.GetString("en_update_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update found.
        /// </summary>
        internal static string en_update_found_title {
            get {
                return ResourceManager.GetString("en_update_found_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version.
        /// </summary>
        internal static string en_update_new {
            get {
                return ResourceManager.GetString("en_update_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying Update ....
        /// </summary>
        internal static string en_update_verifying {
            get {
                return ResourceManager.GetString("en_update_verifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&lt;br/&gt;o&lt;br/&gt;t&lt;br/&gt;&lt;br/&gt;S&lt;br/&gt;u&lt;br/&gt;p&lt;br/&gt;p&lt;br/&gt;o&lt;br/&gt;r&lt;br/&gt;t&lt;br/&gt;e&lt;br/&gt;d.
        /// </summary>
        internal static string en_vertical_not_supported {
            get {
                return ResourceManager.GetString("en_vertical_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get window dimensions!.
        /// </summary>
        internal static string en_window_get_dim_failed {
            get {
                return ResourceManager.GetString("en_window_get_dim_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者.
        /// </summary>
        internal static string zh_about_author_label {
            get {
                return ResourceManager.GetString("zh_about_author_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;关于&lt;/b&gt;.
        /// </summary>
        internal static string zh_about_button {
            get {
                return ResourceManager.GetString("zh_about_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱.
        /// </summary>
        internal static string zh_about_email_label {
            get {
                return ResourceManager.GetString("zh_about_email_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务栏中看小说！&lt;br/&gt;谢谢支持！.
        /// </summary>
        internal static string zh_about_intro {
            get {
                return ResourceManager.GetString("zh_about_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简介.
        /// </summary>
        internal static string zh_about_intro_label {
            get {
                return ResourceManager.GetString("zh_about_intro_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        internal static string zh_about_label {
            get {
                return ResourceManager.GetString("zh_about_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本.
        /// </summary>
        internal static string zh_about_version_label {
            get {
                return ResourceManager.GetString("zh_about_version_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 秒.
        /// </summary>
        internal static string zh_apt_end_label {
            get {
                return ResourceManager.GetString("zh_apt_end_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动翻页.
        /// </summary>
        internal static string zh_apt_label {
            get {
                return ResourceManager.GetString("zh_apt_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒.
        /// </summary>
        internal static string zh_apt_label_sec {
            get {
                return ResourceManager.GetString("zh_apt_label_sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动翻页设置.
        /// </summary>
        internal static string zh_apt_label2 {
            get {
                return ResourceManager.GetString("zh_apt_label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 秒&lt;br/&gt;手动翻页.
        /// </summary>
        internal static string zh_apt_start_label {
            get {
                return ResourceManager.GetString("zh_apt_start_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒.
        /// </summary>
        internal static string zh_apt_tooltip {
            get {
                return ResourceManager.GetString("zh_apt_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新出错！&lt;br/&gt;请稍后再试一次！.
        /// </summary>
        internal static string zh_autoUpdater_msg_failed {
            get {
                return ResourceManager.GetString("zh_autoUpdater_msg_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新出错.
        /// </summary>
        internal static string zh_autoUpdater_msg_failed_title {
            get {
                return ResourceManager.GetString("zh_autoUpdater_msg_failed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新成功！&lt;br/&gt;程序5秒后即将自动重启！.
        /// </summary>
        internal static string zh_autoUpdater_msg_success {
            get {
                return ResourceManager.GetString("zh_autoUpdater_msg_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新成功.
        /// </summary>
        internal static string zh_autoUpdater_msg_success_title {
            get {
                return ResourceManager.GetString("zh_autoUpdater_msg_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新过程被中断！&lt;br/&gt;无法完成更新！.
        /// </summary>
        internal static string zh_autoUpdater_msg_terminated {
            get {
                return ResourceManager.GetString("zh_autoUpdater_msg_terminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新中断.
        /// </summary>
        internal static string zh_autoUpdater_msg_terminated_title {
            get {
                return ResourceManager.GetString("zh_autoUpdater_msg_terminated_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已经是最新版本！.
        /// </summary>
        internal static string zh_autoUpdater_result_latest {
            get {
                return ResourceManager.GetString("zh_autoUpdater_result_latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有找到更新信息！.
        /// </summary>
        internal static string zh_autoUpdater_result_none {
            get {
                return ResourceManager.GetString("zh_autoUpdater_result_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已添加书签！.
        /// </summary>
        internal static string zh_bookmark_added {
            get {
                return ResourceManager.GetString("zh_bookmark_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有书签都已被删除！.
        /// </summary>
        internal static string zh_bookmark_all_deleted {
            get {
                return ResourceManager.GetString("zh_bookmark_all_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除书签出错！.
        /// </summary>
        internal static string zh_bookmark_delete_error {
            get {
                return ResourceManager.GetString("zh_bookmark_delete_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 书签已存在！.
        /// </summary>
        internal static string zh_bookmark_exists {
            get {
                return ResourceManager.GetString("zh_bookmark_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有书签！.
        /// </summary>
        internal static string zh_bookmark_none {
            get {
                return ResourceManager.GetString("zh_bookmark_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本书书签.
        /// </summary>
        internal static string zh_bookmarks {
            get {
                return ResourceManager.GetString("zh_bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空书签.
        /// </summary>
        internal static string zh_bookmarks_clearall {
            get {
                return ResourceManager.GetString("zh_bookmarks_clearall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (无).
        /// </summary>
        internal static string zh_bookmarks_none {
            get {
                return ResourceManager.GetString("zh_bookmarks_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string zh_button_cancel {
            get {
                return ResourceManager.GetString("zh_button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        internal static string zh_button_ok {
            get {
                return ResourceManager.GetString("zh_button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        internal static string zh_exit {
            get {
                return ResourceManager.GetString("zh_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 隐藏/显示.
        /// </summary>
        internal static string zh_hideshow {
            get {
                return ResourceManager.GetString("zh_hideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 历史记录.
        /// </summary>
        internal static string zh_history {
            get {
                return ResourceManager.GetString("zh_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空历史记录.
        /// </summary>
        internal static string zh_history_clearall {
            get {
                return ResourceManager.GetString("zh_history_clearall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除无效记录.
        /// </summary>
        internal static string zh_history_clearinvalid {
            get {
                return ResourceManager.GetString("zh_history_clearinvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (无).
        /// </summary>
        internal static string zh_history_none {
            get {
                return ResourceManager.GetString("zh_history_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;热键说明&lt;/b&gt;.
        /// </summary>
        internal static string zh_hotkey_button {
            get {
                return ResourceManager.GetString("zh_hotkey_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 热键无效！.
        /// </summary>
        internal static string zh_hotkey_invalid_pressed {
            get {
                return ResourceManager.GetString("zh_hotkey_invalid_pressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用说明.
        /// </summary>
        internal static string zh_hotkey_label {
            get {
                return ResourceManager.GetString("zh_hotkey_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 书签模式.
        /// </summary>
        internal static string zh_hotkey_label1 {
            get {
                return ResourceManager.GetString("zh_hotkey_label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 鼠标按键.
        /// </summary>
        internal static string zh_hotkey_label2 {
            get {
                return ResourceManager.GetString("zh_hotkey_label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 键盘热键.
        /// </summary>
        internal static string zh_hotkey_label3 {
            get {
                return ResourceManager.GetString("zh_hotkey_label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一些热键注册失败！.
        /// </summary>
        internal static string zh_hotkey_registration_failed {
            get {
                return ResourceManager.GetString("zh_hotkey_registration_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一行.
        /// </summary>
        internal static string zh_hotkey1 {
            get {
                return ResourceManager.GetString("zh_hotkey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+X.
        /// </summary>
        internal static string zh_hotkey1_label {
            get {
                return ResourceManager.GetString("zh_hotkey1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除当前书签.
        /// </summary>
        internal static string zh_hotkey10 {
            get {
                return ResourceManager.GetString("zh_hotkey10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+D.
        /// </summary>
        internal static string zh_hotkey10_label {
            get {
                return ResourceManager.GetString("zh_hotkey10_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一行.
        /// </summary>
        internal static string zh_hotkey2 {
            get {
                return ResourceManager.GetString("zh_hotkey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+Z.
        /// </summary>
        internal static string zh_hotkey2_label {
            get {
                return ResourceManager.GetString("zh_hotkey2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加当前行为书签.
        /// </summary>
        internal static string zh_hotkey3 {
            get {
                return ResourceManager.GetString("zh_hotkey3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+A.
        /// </summary>
        internal static string zh_hotkey3_label {
            get {
                return ResourceManager.GetString("zh_hotkey3_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换到书签模式.
        /// </summary>
        internal static string zh_hotkey4 {
            get {
                return ResourceManager.GetString("zh_hotkey4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+S.
        /// </summary>
        internal static string zh_hotkey4_label {
            get {
                return ResourceManager.GetString("zh_hotkey4_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换阅读/书签模式.
        /// </summary>
        internal static string zh_hotkey5 {
            get {
                return ResourceManager.GetString("zh_hotkey5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+C.
        /// </summary>
        internal static string zh_hotkey5_label {
            get {
                return ResourceManager.GetString("zh_hotkey5_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示/隐藏 TaskbarReader.
        /// </summary>
        internal static string zh_hotkey6 {
            get {
                return ResourceManager.GetString("zh_hotkey6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+空格.
        /// </summary>
        internal static string zh_hotkey6_label {
            get {
                return ResourceManager.GetString("zh_hotkey6_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出 TaskbarReader.
        /// </summary>
        internal static string zh_hotkey7 {
            get {
                return ResourceManager.GetString("zh_hotkey7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+Q.
        /// </summary>
        internal static string zh_hotkey7_label {
            get {
                return ResourceManager.GetString("zh_hotkey7_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一个书签.
        /// </summary>
        internal static string zh_hotkey8 {
            get {
                return ResourceManager.GetString("zh_hotkey8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+A.
        /// </summary>
        internal static string zh_hotkey8_label {
            get {
                return ResourceManager.GetString("zh_hotkey8_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一个书签.
        /// </summary>
        internal static string zh_hotkey9 {
            get {
                return ResourceManager.GetString("zh_hotkey9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+S.
        /// </summary>
        internal static string zh_hotkey9_label {
            get {
                return ResourceManager.GetString("zh_hotkey9_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示/隐藏 TaskbarReader.
        /// </summary>
        internal static string zh_mouse1 {
            get {
                return ResourceManager.GetString("zh_mouse1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左键双击.
        /// </summary>
        internal static string zh_mouse1_label {
            get {
                return ResourceManager.GetString("zh_mouse1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开TXT.
        /// </summary>
        internal static string zh_mouse2 {
            get {
                return ResourceManager.GetString("zh_mouse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中键单击.
        /// </summary>
        internal static string zh_mouse2_label {
            get {
                return ResourceManager.GetString("zh_mouse2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示右键菜单.
        /// </summary>
        internal static string zh_mouse3 {
            get {
                return ResourceManager.GetString("zh_mouse3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右键单击.
        /// </summary>
        internal static string zh_mouse3_label {
            get {
                return ResourceManager.GetString("zh_mouse3_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只能拖入一个文件！.
        /// </summary>
        internal static string zh_only_single_file {
            get {
                return ResourceManager.GetString("zh_only_single_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只能拖入TXT文件！.
        /// </summary>
        internal static string zh_only_txt_file {
            get {
                return ResourceManager.GetString("zh_only_txt_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开TXT.
        /// </summary>
        internal static string zh_openFile {
            get {
                return ResourceManager.GetString("zh_openFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本文件|*.txt.
        /// </summary>
        internal static string zh_openFileDialog_filter {
            get {
                return ResourceManager.GetString("zh_openFileDialog_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择TXT文件.
        /// </summary>
        internal static string zh_openFileDialog_title {
            get {
                return ResourceManager.GetString("zh_openFileDialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拖拽TXT文件到框内.
        /// </summary>
        internal static string zh_pictureBox_string_1 {
            get {
                return ResourceManager.GetString("zh_pictureBox_string_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 或者双击框内.
        /// </summary>
        internal static string zh_pictureBox_string_2 {
            get {
                return ResourceManager.GetString("zh_pictureBox_string_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在阅读：.
        /// </summary>
        internal static string zh_pictureBox_string_3 {
            get {
                return ResourceManager.GetString("zh_pictureBox_string_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已是第一行！.
        /// </summary>
        internal static string zh_readbackward_nomore {
            get {
                return ResourceManager.GetString("zh_readbackward_nomore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已是最后一行！.
        /// </summary>
        internal static string zh_readforward_nomore {
            get {
                return ResourceManager.GetString("zh_readforward_nomore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效指令！.
        /// </summary>
        internal static string zh_timer_error {
            get {
                return ResourceManager.GetString("zh_timer_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已完成：.
        /// </summary>
        internal static string zh_update_completed {
            get {
                return ResourceManager.GetString("zh_update_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前版本.
        /// </summary>
        internal static string zh_update_cur {
            get {
                return ResourceManager.GetString("zh_update_cur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新内容.
        /// </summary>
        internal static string zh_update_description {
            get {
                return ResourceManager.GetString("zh_update_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载更新.
        /// </summary>
        internal static string zh_update_download {
            get {
                return ResourceManager.GetString("zh_update_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已下载：.
        /// </summary>
        internal static string zh_update_downloaded {
            get {
                return ResourceManager.GetString("zh_update_downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在下载更新…….
        /// </summary>
        internal static string zh_update_downloading {
            get {
                return ResourceManager.GetString("zh_update_downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有新版本发布！.
        /// </summary>
        internal static string zh_update_found {
            get {
                return ResourceManager.GetString("zh_update_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测到更新.
        /// </summary>
        internal static string zh_update_found_title {
            get {
                return ResourceManager.GetString("zh_update_found_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新版本.
        /// </summary>
        internal static string zh_update_new {
            get {
                return ResourceManager.GetString("zh_update_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证更新…….
        /// </summary>
        internal static string zh_update_verifying {
            get {
                return ResourceManager.GetString("zh_update_verifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支持竖任务栏.
        /// </summary>
        internal static string zh_vertical_not_supported {
            get {
                return ResourceManager.GetString("zh_vertical_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法获得窗口尺寸！.
        /// </summary>
        internal static string zh_window_get_dim_failed {
            get {
                return ResourceManager.GetString("zh_window_get_dim_failed", resourceCulture);
            }
        }
    }
}
